![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [64]:
# Import necessary packages
import pandas as pd
import numpy as np

**1 - Loading the data**

In [65]:
airbnb_price = pd.read_csv('data/airbnb_price.csv')
airbnb_price.head()

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [66]:
airbnb_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
airbnb_room_type.head()

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [67]:
airbnb_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep = '\t')
airbnb_last_review.head()

   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

**2 - Merging the three DataFrames**

In [68]:
airbnb = airbnb_price.merge(airbnb_room_type, on = 'listing_id', how = 'inner')
airbnb = airbnb.merge(airbnb_last_review, on = 'listing_id', how = 'inner')
airbnb.head()

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

**3 - Determining the earliest and most recent review dates**

**3-a - Converting reviews data to a date format**

In [69]:
airbnb['last_review_date'] = pd.to_datetime(airbnb['last_review'])
airbnb['last_review_date'].head()

0   2019-05-21
1   2019-07-05
2   2019-06-22
3   2019-06-24
4   2019-06-09
Name: last_review_date, dtype: datetime64[ns]

**3-b - Finding the earliest and most recent dates**

In [70]:
earliest_review_date = airbnb['last_review_date'].min().date()
most_recent_review_date = airbnb['last_review_date'].max().date()
print([earliest_review_date, most_recent_review_date])

[datetime.date(2019, 1, 1), datetime.date(2019, 7, 9)]

**4 - Finding how many listings are private rooms**

In [71]:
airbnb['room_type'].unique()

array(['Entire home/apt', 'private room', 'Private room',
       'entire home/apt', 'PRIVATE ROOM', 'shared room',
       'ENTIRE HOME/APT', 'Shared room', 'SHARED ROOM'], dtype=object)

**4-a - Cleaning data with pandas**

In [72]:
airbnb['room_type'] = airbnb['room_type'].str.lower()
airbnb['room_type'].unique()

array(['entire home/apt', 'private room', 'shared room'], dtype=object)

**4-b - Counting the number of private rooms**

In [73]:
private_rooms_count = len(airbnb[airbnb['room_type'] == 'private room'])
private_rooms_count

11356

**5 - Finding the average price of listings**

**5-a - Converting to numeric type**

In [74]:
airbnb['price'] = airbnb['price'].str.replace(" dollars", "").astype("float")

In [75]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        25209 non-null  int64
 1   price             25209 non-null  float64
 2   nbhood_full       25209 non-null  object
 3   description       25199 non-null  object
 4   room_type         25209 non-null  object
 5   host_name         25201 non-null  object
 6   last_review       25209 non-null  object
 7   last_review_date  25209 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 1.7+ MB

**5-b - Finding the mean**

In [76]:
avg_price = round(airbnb['price'].mean(), 2)
avg_price

141.78

**6 - Creating a DataFrame with the four solution values**

In [77]:
data = {
    "first_reviewed": [earliest_review_date],
    "last_reviewed": [most_recent_review_date],
    "nb_private_rooms": [private_rooms_count],
    "avg_price": [avg_price]
}
review_dates = pd.DataFrame(data)
review_dates

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78